#!/bin/bash

OK=0
#WARNING=1
CRITICAL=2
#UNKNOWN=3

sudo su - node -c "pm2 ls |grep 'errored \| stopped'" > /dev/null

status=$?

#echo $status

if [ $status -eq 0 ];then
	app_status=$(sudo su - node -c "pm2 ls |grep 'errored \| stopped' | awk '{print \$2, \$10}'")
	echo -e "NODE STATUS: CRITICAL \n$app_status"
	exit $CRITICAL
else
   echo "NODE STATUS: OK ONLINE"
fi
