#!/bin/bash
#Check for the process having greater than threshold CPU Utilisation
critical="70.0"
warning="40.0"
current_top_proc_cpu=`ps -eo pcpu,pid,user,args | sort -k1 -r | sed -n '1!p' | head -1 |awk {'print$1'}`
proc_name=`ps -eo pcpu,pid,user,args | sort -k1 -r | sed -n '1!p' | head -1 |awk {'print$4$5$6$7$8'}`
flag1=`echo $current_top_proc_cpu '>' $critical | bc -l`
flag2=`echo $current_top_proc_cpu '>' $warning | bc -l`
if [[ "$flag1" == "1" ]]
then
    echo "CRITICAL : Process with Max CPU Utilisation : '$proc_name'('$current_top_proc_cpu'% which is more than '$critical')"
    exit 2

elif [[ "$flag2" == "1" ]]
then
    echo "WARNING : Process with Max CPU Utilisation : '$proc_name'('$current_top_proc_cpu'% which is more than '$warning')"
    exit 1

else
    echo "OK : Process with Max CPU Utilisation :'$proc_name'('$current_top_proc_cpu'%)"
    exit 0
fi
